modLoader="javafml"
loaderVersion="[56,)"
license="MIT"
[[mods]]
modId="relics"
version="1.0.0"
displayName="Relics of the Endfire"
description="Adds mythic weapons, cursed totems, and deadly bosses."
